### ISSUE TITLE
Crash on reading BIN file

### ISSUE THREAD

**Issue by milosmns** [ip2location/ip2location-java#4]
## The problem

Lib crashing on file load.

## Steps to reproduce

1. Download the latest BIN files from https://www.ip2location.com/download/?token=my_token_here&file=DB3LITEBIN and https://www.ip2location.com/download/?token=my_token_here&file=DB3LITEBINIPV6
2. Verify files are non-null and have realistic sizes
3. Use a Spring Boot app, put the files in `resources/ip2location` folder with names `IPv4.bin` and `IPv6.bin` respectively

Some sample code I have:
_(it's Kotlin but doesn't matter, it's almost identical in Java)_

```kotlin
// skipped imports

private const val PATH_V4 = "ip2location/IPv4.bin"
private const val PATH_V6 = "ip2location/IPv6.bin"

@Component
class GeolocationDaoLocalFile : GeolocationDao {

  private val log = LoggerFactory.getLogger(this::class.java)

  private val ipv4Locator = IP2Location()
  private val ipv6Locator = IP2Location()

  @PostConstruct
  fun setup() {
    val loader = Thread.currentThread().contextClassLoader // valid, used in other places
    val v4Resource = loader.getResource(PATH_V4) // valid, verified in debug mode
    val v6Resource = loader.getResource(PATH_V6) // valid as well
    ipv4Locator.Open(v4Resource!!.file)   //  <---------  this is where it crashes
    ipv6Locator.Open(v6Resource!!.file)
  }

  @PreDestroy
  fun teardown() = try {
    ipv4Locator.Close()
    ipv6Locator.Close()
  } catch (t: Throwable) {
    log.error("Failed to close IP locator", t)
  }

  override fun fetchGeolocationForIp(ipAddress: String) = requireNotNull(
    ipv4Locator.IPQuery(ipAddress)?.toDomain()
      ?: ipv6Locator.IPQuery(ipAddress)?.toDomain()
  )

}
```

## The crash

```log
Index 80 out of bounds for length 25
java.lang.ArrayIndexOutOfBoundsException: Index 80 out of bounds for length 25
	at com.ip2location.IP2Location.LoadBIN(IP2Location.java:322)
	at com.ip2location.IP2Location.Open(IP2Location.java:156)
```

That's the line:

```java
COUNTRY_POSITION_OFFSET = (COUNTRY_POSITION[dbtype] != 0) ? (COUNTRY_POSITION[dbtype] - 2) << 2 : 0;
```

I debugged, `dbtype` is `80` in this case... so it's out of bounds.

-----

I'd be happy with CSV as well if that was any easier to access at random... but it's worse than BIN in most ways.

**Comment by ip2location** [comment]
After you've downloaded the ZIP file containing the BIN, did you extract the BIN file first? Or did you treat the ZIP file as BIN?

**Comment by ip2location** [comment]
Also please note that the IPv6 BIN contains both IPv4 and IPv6 so you don't need to use both BIN files.

**Comment by milosmns** [comment]
Oh good point, let me check on both things and get back to you! Thanks for
that!

**Comment by milosmns** [comment]
### Update

I'm downloading a newer version of the file for each QA (CI) build, but due to the limitation of 5 downloads per hour, sometimes this download doesn't happen. I still have it stored in the repo, but it's not a fresh version.

So I found out what it was. I had a bug in the script that didn't actually unzip the old file in the scenario when I can't download the new file... it only unzips the newly downloaded file 🤦 

Thanks for that tip, it led me to the right solution. 👍
